// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWAP4rltCyYY1m49wxPR0MsAjKx1cBQQ0',
    appId: '1:755392738402:web:4900aebc15ab3d24018d3b',
    messagingSenderId: '755392738402',
    projectId: 'cbappitesa',
    authDomain: 'cbappitesa.firebaseapp.com',
    storageBucket: 'cbappitesa.appspot.com',
    measurementId: 'G-FZCLBTZ5RF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIUISdQRH_RjqDwHLr0jTNpcrSa1mD0NQ',
    appId: '1:755392738402:android:a37fff0121c422fb018d3b',
    messagingSenderId: '755392738402',
    projectId: 'cbappitesa',
    storageBucket: 'cbappitesa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSL_EvL8j-kRkcFQETXa7l7qe-tz105qg',
    appId: '1:755392738402:ios:eafc495b28e20335018d3b',
    messagingSenderId: '755392738402',
    projectId: 'cbappitesa',
    storageBucket: 'cbappitesa.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSL_EvL8j-kRkcFQETXa7l7qe-tz105qg',
    appId: '1:755392738402:ios:eafc495b28e20335018d3b',
    messagingSenderId: '755392738402',
    projectId: 'cbappitesa',
    storageBucket: 'cbappitesa.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWAP4rltCyYY1m49wxPR0MsAjKx1cBQQ0',
    appId: '1:755392738402:web:4900aebc15ab3d24018d3b',
    messagingSenderId: '755392738402',
    projectId: 'cbappitesa',
    authDomain: 'cbappitesa.firebaseapp.com',
    storageBucket: 'cbappitesa.appspot.com',
    measurementId: 'G-FZCLBTZ5RF',
  );

}